apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/app: devopsapp
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 8080
      targetPort: 8080
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      #nodePort: 30007
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-config
data:
  config.json: |
    {
      "auths": {
        "https://naik.jfrog.io": {
          "username": "praveenaik009@gmail.com",
          "password": "Praveen009",
          "auth": "cHJhdmVuYWlrMDA5QGdtYWlsLmNvbTpQcmF2ZWVuMDA5"
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsapp-deployment
  labels:
    app: devopsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsapp
  template:
    metadata:
      labels:
        app: devopsapp
    spec:
      containers:
      - name: devopsapp
        image: naik.jfrog.io/artifactory/mydocker-docker-local/testimage:${BUILD_NUMBER}
        ports:
        - containerPort: 8080
      imagePullSecrets: 
      - name: my-artifactory-cred
        envFrom:
          - configMapRef:
              name: docker-config
